name: Firebase Deploy

on:
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: node version

      - uses: actions/cache@v1.2.0
        with:
          path: Library
          key: Library

      - uses: webbertakken/unity-builder@main
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 2019.3.6f1
          targetPlatform: WebGL
          versioning: None

      - uses: actions/upload-artifact@main
        with:
          name: build
          path: build/WebGL/WebGL

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/checkout@main

      - uses: actions/download-artifact@main
        with:
          name: build
          path: build

      - uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
